# This is a basic workflow to help you get started with Actions

name: Notify Test

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'success or fail'
        required: true
        default: 'success'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: success
        if: ${{ github.event.inputs.status == 'success' }}
        run: exit 0
      - name: fail
        if: ${{ github.event.inputs.status == 'fail' }}
        run: exit 1
        
  slack-notify-success:
    name: Slack Notify on success
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [job-1, job-2]
    if: always()
    steps:
    - name: Set Variables
      id: var 
      run: |
        if [ ${{ needs.job-1.result }} = "success" ] && \
           [ ${{ needs.job-2.result }} = "success" ]; then
          echo "::set-output name=TEXT::Successfully"
          echo "::set-output name=STATUS_MOJI:::white_check_mark:"
        else
          echo "::set-output name=TEXT::Unsuccessfully"
          echo "::set-output name=STATUS_MOJI:::x:" 
        fi

    - name: Slack Notification
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        blocks: |
          [
          		{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Result* \ndata-visualization-3rd: ${{ steps.var.outputs.TEXT }} automated deployment ${{ steps.var.outputs.STATUS_MOJI}}"
                }
              },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Workflow* \n${{ github.workflow }}"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*GitHub Actions URL*\nhttps://github.com/eightcard/randd_data_visualization/actions/runs/${{ github.run_id }}\n"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Input Variables* \nstatus: ${{ github.event.inputs.status }} "
              }
            }
          ]
