# This is a basic workflow to help you get started with Actions

name: Notify Test

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'success or fail'
        required: true
        default: 'success'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: success
        if: ${{ github.event.inputs.status == 'success' }}
        run: exit 0
      - name: fail
        if: ${{ github.event.inputs.status == 'fail' }}
        run: exit 1
        
  slack-notify-success:
    name: Slack Notify on success
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [job-1, job-2]
    if: success()
    steps:
    - name: Set Variables on Success
      run: echo "COLOR=good" >> $GITHUB_ENV && echo "TEXT=Successfully" >> $GITHUB_ENV
    - name: Set COMMIT_MESSAGE
      run: echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
    - name: Slack Notification
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: ${{env.TEXT}} automated deployment.
        attachments: |
          [
            {
              "color": "${{env.COLOR}}",
              "fields": [
                {
                  "title": "Commit Message",
                  "value": "${{ env.COMMIT_MESSAGE }}"
                },
                {
                  "title": "GitHub Actions URL",
                  "value": "https://github.com/Nishikoh/actions-practice/actions/runs/${{ github.run_id }}"
                },
                {
                  "title": "Workflow Name",
                  "value": "${{ github.workflow }}"
                },
                {
                  "title": "Input Variables",
                  "value": "status: ${{ github.event.inputs.status }}",
                  "value": "hoge"
                }
              ]
            }
          ]
          
  slack-notify-fail:
    name: Slack Notify on Failure
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [job-1, job-2]
    if: failure()
    steps:
    - name: Set Variables on Success
      run: echo "COLOR=danger" >> $GITHUB_ENV && echo "TEXT=Fail" >> $GITHUB_ENV
    - name: Set COMMIT_MESSAGE
      run: echo "COMMIT_MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
    - name: Slack Notification
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: ${{env.TEXT}} automated deployment.
        attachments: |
          [
            {
              "color": "${{env.COLOR}}",
              "fields": [
                {
                  "title": "Commit Message",
                  "value": "${{ env.COMMIT_MESSAGE }}"
                },
                {
                  "title": "GitHub Actions URL",
                  "value": "https://github.com/Nishikoh/actions-practice/actions/runs/${{ github.run_id }}"
                },
                {
                  "title": "Workflow Name",
                  "value": "${{ github.workflow }}"
                },
                {
                  "title": "Input Variables",
                  "value": "status: ${{ github.event.inputs.status }}",
                  "value": "hoge"
                }
              ]
            }
          ]

